"""
================================================================================
KENYA AIRWAYS — AIR TICKET PRICE FORECASTING  •  REST API
================================================================================

PURPOSE
───────
Exposes the three trained forecasting models (ARIMA, Standalone LSTM,
ARIMA-LSTM Hybrid) as a JSON REST API using FastAPI.  This layer sits between
the trained model artifacts and any downstream consumer — the Streamlit
dashboard, a revenue management system, a mobile app, or a scheduled job —
decoupling inference from the UI and enabling programmatic access to forecasts.

SYSTEM ARCHITECTURE
───────────────────

  ┌─────────────────────────────┐
  │  Raw Booking Data (Excel)   │
  └──────────────┬──────────────┘
                 │  pipeline.py (daily cron)
                 ▼
  ┌─────────────────────────────┐     ┌──────────────────────────────┐
  │  forecasting.db (SQLite)    │◄────│  Trained Model Artifacts     │
  │  forecasts / actuals /      │     │  artifacts/                  │
  │  performance_metrics /      │     │  ├── arima_model.pkl         │
  │  pipeline_runs              │     │  ├── standalone_lstm.keras   │
  └──────────────┬──────────────┘     │  ├── hybrid_lstm.keras       │
                 │                    │  ├── price_scaler.pkl        │
                 │  api.py            │  ├── residual_scaler.pkl     │
                 ▼  (this file)       │  ├── exog_scaler.pkl         │
  ┌─────────────────────────────┐     │  └── model_meta.pkl          │
  │  FastAPI REST endpoints     │◄────┘
  │                             │
  │  GET  /health               │
  │  GET  /routes               │
  │  GET  /forecast/latest      │
  │  POST /forecast/custom      │
  │  GET  /performance          │
  │  GET  /pipeline/runs        │
  └──────────────┬──────────────┘
                 │
        ┌────────┴────────┐
        ▼                 ▼
  Streamlit          Revenue Mgmt
  dashboard.py       System / Excel
  (internal)         (external)

RUNNING THE API
───────────────
    # Install dependencies (once)
    pip install fastapi uvicorn

    # Start the server
    uvicorn api:app --host 0.0.0.0 --port 8000 --reload

    # Interactive API docs (auto-generated by FastAPI)
    http://localhost:8000/docs      ← Swagger UI
    http://localhost:8000/redoc     ← ReDoc

    # Example curl calls
    curl http://localhost:8000/health
    curl "http://localhost:8000/forecast/latest?route=NBO-MBA&horizon=30"
    curl -X POST http://localhost:8000/forecast/custom \\
         -H "Content-Type: application/json" \\
         -d '{"prices": [310,315,322,318,325,330,328], "horizon": 14}'

THESIS CONTEXT  (Section 3.10 — Deployment)
────────────────────────────────────────────
This API constitutes the production deployment layer described in the thesis
proposal.  In a Kenya Airways production environment it would be:

  • Containerised with Docker and deployed to a cloud VM or Kubernetes pod
  • Secured with API-key authentication (see AUTH_KEY below)
  • Queried daily by the revenue management system to pull updated price
    forecasts into fare-setting workflows
  • Monitored via the /health and /pipeline/runs endpoints by an Airflow DAG

For the purposes of this thesis, the API runs locally and is demonstrated via
the interactive Swagger UI at /docs.

DEPENDENCIES
────────────
    fastapi      — async web framework with automatic OpenAPI schema generation
    uvicorn      — ASGI server
    numpy        — array operations
    pandas       — DataFrame handling
    joblib       — artifact deserialisation
    tensorflow   — LSTM model inference (loaded once at startup)
    statsmodels  — ARIMA refitting for custom endpoint
================================================================================
"""
from loader import download_if_missing
download_if_missing()

import os
import sqlite3
import warnings
from datetime import datetime, timedelta
from pathlib import Path
from typing import List, Optional

import joblib
import numpy as np
import pandas as pd
import uvicorn

warnings.filterwarnings('ignore')

from fastapi import FastAPI, HTTPException, Query, Depends
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, validator

# ─── Optional auth (set KQ_API_KEY env var to enable) ────────────────────────
# In production this would be replaced with OAuth2 / JWT.
# For thesis demonstration, a simple shared secret header is sufficient.
AUTH_KEY = os.getenv('KQ_API_KEY', '')   # empty string = auth disabled

# ─── Paths (mirror pipeline.py) ───────────────────────────────────────────────
BASE_DIR     = Path(__file__).parent
ARTIFACT_DIR = Path(os.getenv('KQ_ARTIFACT_DIR', str(BASE_DIR / 'artifacts')))
DB_PATH      = Path(os.getenv('KQ_DB_PATH',      str(BASE_DIR / 'forecasting.db')))

# ─── Model constants (must match training pipeline) ───────────────────────────
SEQUENCE_LENGTH  = 30    # Standalone LSTM look-back window
HYBRID_SEQ_LEN   = 14    # Hybrid LSTM residual look-back window
SEASONAL_M       = 7     # Weekly seasonality period


# ═════════════════════════════════════════════════════════════════════════════
# PYDANTIC SCHEMAS  (request / response shapes — also generate the API docs)
# ═════════════════════════════════════════════════════════════════════════════

class CustomForecastRequest(BaseModel):
    """
    Request body for POST /forecast/custom.
    The caller supplies raw historical daily prices; the API runs all three
    models and returns forecasts for the requested horizon.
    """
    prices: List[float] = Field(
        ...,
        min_items=10,
        description="Ordered list of historical daily average prices (USD). "
                    "Minimum 10 values; 30+ recommended for reliable results.",
        example=[310, 315, 308, 322, 318, 325, 330, 328, 335, 340,
                 338, 345, 342, 350, 348, 355, 360, 358, 362, 368,
                 365, 370, 375, 372, 378, 380, 385, 382, 388, 390]
    )
    horizon: int = Field(
        30, ge=1, le=90,
        description="Number of days ahead to forecast (1–90)."
    )
    seasonal_m: int = Field(
        7, ge=2, le=14,
        description="Seasonal period in days. Default 7 (weekly)."
    )
    confidence: float = Field(
        0.95, ge=0.5, le=0.99,
        description="Confidence level for prediction intervals (default 95%)."
    )

    @validator('prices')
    def prices_must_be_positive(cls, v):
        if any(p <= 0 for p in v):
            raise ValueError('All prices must be positive.')
        return v


class ForecastPoint(BaseModel):
    date: str
    predicted_price: float
    lower_ci: float
    upper_ci: float
    horizon_day: int


class ModelForecast(BaseModel):
    model: str
    points: List[ForecastPoint]
    mean_price: float
    min_price:  float
    max_price:  float


class ForecastResponse(BaseModel):
    route:         str
    generated_at:  str
    horizon_days:  int
    forecasts:     List[ModelForecast]
    recommended_model: Optional[str] = None
    note:          Optional[str] = None


class HealthResponse(BaseModel):
    status:          str
    db_reachable:    bool
    artifacts_loaded: bool
    last_pipeline_run: Optional[str]
    models_available:  List[str]


class PerformanceResponse(BaseModel):
    route:    str
    results:  List[dict]
    source:   str     # 'database' | 'thesis_test_set'


class PipelineRun(BaseModel):
    run_id:          str
    started_at:      str
    finished_at:     Optional[str]
    status:          str
    n_rows_raw:      Optional[int]
    n_rows_processed: Optional[int]
    n_routes:        Optional[int]


# ═════════════════════════════════════════════════════════════════════════════
# MODEL REGISTRY  (loaded once at startup — not per-request)
# ═════════════════════════════════════════════════════════════════════════════
class ModelRegistry:
    """
    Holds all trained model artifacts in memory.  Loaded once when the API
    process starts; subsequent requests pay zero disk-read cost.

    This singleton pattern is standard in production ML APIs: model loading
    (especially Keras models) is expensive (1-5 seconds), so it must not
    happen on the hot path of each request.
    """
    def __init__(self):
        self.arima      = None
        self.sa_lstm    = None
        self.hy_lstm    = None
        self.price_sc   = None
        self.res_sc     = None
        self.exog_sc    = None
        self.encoders   = None
        self.meta       = {}
        self.loaded     = False
        self._errors    = []

    def load(self, artifact_dir: Path) -> None:
        """
        Attempt to load all artifacts.  Failures are recorded but do not crash
        the server — the /health endpoint will report which models are missing,
        and endpoints that require them will return 503.
        """
        self._errors = []
        try:
            import tensorflow as tf
            self.sa_lstm  = tf.keras.models.load_model(
                artifact_dir / 'standalone_lstm_model.keras', compile=False)
            self.hy_lstm  = tf.keras.models.load_model(
                artifact_dir / 'hybrid_lstm_model.keras', compile=False)
        except Exception as e:
            self._errors.append(f'Keras models: {e}')

        for attr, fname in [
            ('arima',    'arima_model.pkl'),
            ('price_sc', 'price_scaler.pkl'),
            ('res_sc',   'residual_scaler.pkl'),
            ('exog_sc',  'exog_scaler.pkl'),
            ('encoders', 'label_encoders.pkl'),
            ('meta',     'model_meta.pkl'),
        ]:
            try:
                setattr(self, attr, joblib.load(artifact_dir / fname))
            except Exception as e:
                self._errors.append(f'{fname}: {e}')

        self.loaded = len(self._errors) == 0

    @property
    def available_models(self) -> List[str]:
        out = []
        if self.arima   is not None: out.append('ARIMA')
        if self.sa_lstm is not None: out.append('Standalone LSTM')
        if self.sa_lstm is not None and self.hy_lstm is not None:
            out.append('ARIMA-LSTM Hybrid')
        return out


registry = ModelRegistry()


# ═════════════════════════════════════════════════════════════════════════════
# DATABASE HELPERS
# ═════════════════════════════════════════════════════════════════════════════
def get_db() -> sqlite3.Connection:
    """
    Dependency-injected DB connection (FastAPI Depends pattern).
    SQLite is used here for portability; in a production KQ deployment this
    would be replaced with a PostgreSQL connection pool (e.g. asyncpg).
    """
    if not DB_PATH.exists():
        raise HTTPException(
            status_code=503,
            detail=f"Database not found at {DB_PATH}. Run pipeline.py first."
        )
    conn = sqlite3.connect(str(DB_PATH), check_same_thread=False)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
    finally:
        conn.close()


def _query(conn: sqlite3.Connection, sql: str,
           params: tuple = ()) -> pd.DataFrame:
    try:
        return pd.read_sql_query(sql, conn, params=params)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"DB query failed: {e}")


# ═════════════════════════════════════════════════════════════════════════════
# INFERENCE HELPERS  (stateless — called on every /forecast/custom request)
# ═════════════════════════════════════════════════════════════════════════════
def _arima_forecast(prices: np.ndarray, horizon: int) -> tuple:
    """
    Refit ARIMA on provided prices and produce a horizon-step forecast.
    Returns (forecast_array, residual_std).

    The ARIMA order is taken from the stored artifact if available; otherwise
    falls back to (1,1,1) which is a reasonable default for differenced
    airline price series.
    """
    from statsmodels.tsa.statespace.sarimax import SARIMAX
    try:
        order = getattr(registry.arima, 'order', (1, 1, 1))
        seas  = getattr(registry.arima, 'seasonal_order', (0, 0, 0, 0))
        m = SARIMAX(
            prices.astype(float),
            order=order,
            seasonal_order=seas,
            enforce_stationarity=False,
            enforce_invertibility=False
        ).fit(disp=False)
        return m.forecast(steps=horizon), float(np.std(m.resid)), m.resid
    except Exception:
        # Graceful fallback: seasonal naïve
        s = 7
        fc = np.array([prices[-(s - i % s)] for i in range(horizon)])
        return fc, float(np.std(prices) * 0.3), np.zeros(len(prices))


def _sa_lstm_forecast(prices: np.ndarray, horizon: int) -> np.ndarray:
    """
    Recursive standalone LSTM forecast.
    Scales prices with the training-time scaler, runs the model step-by-step,
    and inverse-transforms the output back to USD.
    """
    seq = registry.meta.get('seq_len', SEQUENCE_LENGTH)
    sc  = registry.price_sc
    scaled = sc.transform(prices.reshape(-1, 1)).flatten()
    hist   = list(scaled[-seq:])
    preds  = []
    for _ in range(horizon):
        win = np.array(hist[-seq:]).reshape(1, seq, 1)
        p_s = registry.sa_lstm.predict(win, verbose=0)[0, 0]
        preds.append(float(sc.inverse_transform([[p_s]])[0, 0]))
        hist.append(p_s)
    return np.array(preds)


def _hybrid_forecast(arima_fc: np.ndarray,
                     arima_resid: np.ndarray,
                     horizon: int) -> np.ndarray:
    """
    ARIMA-LSTM Hybrid: ARIMA linear component + LSTM-predicted residual
    correction.  Mirrors the thesis architecture (Section 3.5.3 / Eq. 4).
    """
    seq    = registry.meta.get('hybrid_seq_len', HYBRID_SEQ_LEN)
    res_sc = registry.res_sc
    scaled = res_sc.transform(arima_resid.reshape(-1, 1)).flatten()
    hist   = list(scaled[-seq:])
    n_exog = registry.hy_lstm.input[1].shape[-1]
    exog_ph = np.zeros((1, seq, n_exog))
    corr = []
    for _ in range(horizon):
        rw  = np.array(hist[-seq:]).reshape(1, seq, 1)
        c_s = registry.hy_lstm.predict([rw, exog_ph], verbose=0)[0, 0]
        corr.append(float(res_sc.inverse_transform([[c_s]])[0, 0]))
        hist.append(c_s)
    return np.maximum(arima_fc + np.array(corr), 0.0)


def _build_ci(predictions: np.ndarray, resid_std: float,
              confidence: float = 0.95) -> tuple:
    """Empirical symmetric CI from residual standard deviation."""
    from scipy import stats
    z = float(stats.norm.ppf((1 + confidence) / 2))
    return predictions - z * resid_std, predictions + z * resid_std


def _package_forecast(model_name: str,
                       fc: np.ndarray,
                       lower: np.ndarray,
                       upper: np.ndarray,
                       start_date: datetime) -> ModelForecast:
    points = [
        ForecastPoint(
            date=(start_date + timedelta(days=i)).strftime('%Y-%m-%d'),
            predicted_price=round(float(p), 2),
            lower_ci=round(float(lo), 2),
            upper_ci=round(float(hi), 2),
            horizon_day=i + 1
        )
        for i, (p, lo, hi) in enumerate(zip(fc, lower, upper))
    ]
    return ModelForecast(
        model=model_name, points=points,
        mean_price=round(float(fc.mean()), 2),
        min_price =round(float(fc.min()),  2),
        max_price =round(float(fc.max()),  2),
    )


# ═════════════════════════════════════════════════════════════════════════════
# THESIS TEST-SET RESULTS  (fallback when DB has no performance_metrics yet)
# ═════════════════════════════════════════════════════════════════════════════
THESIS_TEST_RESULTS = [
    {'model': 'Naïve (Seasonal)', 'mae': 28.49, 'rmse': 31.65,
     'mape': 78.04, 'r2': 0.12,  'n_obs': 274, 'split': 'test'},
    {'model': 'ARIMA',            'mae': 14.87, 'rmse': 17.62,
     'mape': 35.54, 'r2': 0.61,  'n_obs': 274, 'split': 'test'},
    {'model': 'Standalone LSTM',  'mae':  5.98, 'rmse':  7.11,
     'mape': 18.41, 'r2': 0.89,  'n_obs': 258, 'split': 'test'},
    {'model': 'ARIMA-LSTM Hybrid','mae':  8.43, 'rmse': 10.22,
     'mape': 22.17, 'r2': 0.84,  'n_obs': 260, 'split': 'test'},
]


# ═════════════════════════════════════════════════════════════════════════════
# APP INITIALISATION
# ═════════════════════════════════════════════════════════════════════════════
app = FastAPI(
    title       = "Kenya Airways — Air Ticket Price Forecasting API",
    description = (
        "REST API serving ARIMA, Standalone LSTM, and ARIMA-LSTM Hybrid "
        "price forecasts for Kenya Airways routes.  Developed as part of an "
        "MSc Data Science & Analytics thesis at Strathmore University.\n\n"
        "**Author:** Dorcas Engasia Misango  \n"
        "**Supervisor:** Dr. Joseph Sevilla  \n"
        "**Admission No.:** 100235"
    ),
    version     = "1.0.0",
    contact     = {
        "name" : "Strathmore University — MSc DSA",
        "email": "d.misango@strathmore.edu",
    },
    license_info = {"name": "Academic use only"},
)


from loader import download_if_missing

@app.on_event("startup")
async def _startup():
    """
    Load all model artifacts into memory when the server starts.
    Failures are logged but do not prevent the server from starting — the
    /health endpoint will surface which models are unavailable.
    """
    print(f"[startup] Loading artifacts from {ARTIFACT_DIR} …")
    registry.load(ARTIFACT_DIR)
    if registry.loaded:
        print(f"[startup] ✅  All artifacts loaded. "
              f"Models available: {registry.available_models}")
    else:
        print(f"[startup] ⚠️  Partial load. Errors:\n" +
              "\n".join(f"  • {e}" for e in registry._errors))


# ═════════════════════════════════════════════════════════════════════════════
# ENDPOINT 1 — HEALTH CHECK
# ═════════════════════════════════════════════════════════════════════════════
@app.get(
    "/health",
    response_model=HealthResponse,
    summary="API health check",
    tags=["Infrastructure"],
    description=(
        "Returns API status, database connectivity, model availability, and "
        "the timestamp of the most recent successful pipeline run.  Suitable "
        "for use as a liveness/readiness probe in a Kubernetes deployment or "
        "as a scheduled Airflow health-check task."
    )
)
def health_check():
    # DB probe
    db_ok = False
    last_run = None
    try:
        conn = sqlite3.connect(str(DB_PATH))
        row = conn.execute(
            "SELECT started_at FROM pipeline_runs "
            "WHERE status='SUCCESS' ORDER BY started_at DESC LIMIT 1"
        ).fetchone()
        db_ok  = True
        last_run = row[0] if row else None
        conn.close()
    except Exception:
        pass

    return HealthResponse(
        status           = "ok" if (db_ok and registry.loaded) else "degraded",
        db_reachable     = db_ok,
        artifacts_loaded = registry.loaded,
        last_pipeline_run = last_run,
        models_available  = registry.available_models,
    )


# ═════════════════════════════════════════════════════════════════════════════
# ENDPOINT 2 — LIST ROUTES
# ═════════════════════════════════════════════════════════════════════════════
@app.get(
    "/routes",
    summary="List available routes",
    tags=["Forecasts"],
    description=(
        "Returns all route codes for which forecast data exists in the "
        "database.  Used by the dashboard sidebar and by downstream systems "
        "to discover which routes the model currently covers."
    )
)
def list_routes(conn: sqlite3.Connection = Depends(get_db)):
    df = _query(conn, "SELECT DISTINCT route FROM forecasts ORDER BY route")
    if df.empty:
        return {"routes": [], "note": "No forecasts in database yet. Run pipeline.py first."}
    return {"routes": df['route'].tolist()}


# ═════════════════════════════════════════════════════════════════════════════
# ENDPOINT 3 — LATEST DB FORECAST  (fast path — no inference)
# ═════════════════════════════════════════════════════════════════════════════
@app.get(
    "/forecast/latest",
    response_model=ForecastResponse,
    summary="Retrieve the latest stored forecast",
    tags=["Forecasts"],
    description=(
        "Returns the most recently stored forecast for a given route from the "
        "SQLite database — **no model inference is performed**.  This is the "
        "fast path for the Streamlit dashboard and revenue management system: "
        "the pipeline runs once daily and pre-computes forecasts; this endpoint "
        "simply serves the pre-computed results.  "
        "Response time is typically < 50 ms."
    )
)
def forecast_latest(
    route:   str = Query('NBO-MBA', description="Route code, e.g. NBO-MBA"),
    horizon: int = Query(30,        ge=1, le=90,
                         description="Number of forecast days to return"),
    models:  str = Query('ARIMA,Standalone LSTM,ARIMA-LSTM Hybrid',
                         description="Comma-separated list of models to include"),
    conn: sqlite3.Connection = Depends(get_db)
):
    # Resolve latest successful run
    run_df = _query(conn,
        "SELECT run_id FROM pipeline_runs "
        "WHERE status='SUCCESS' ORDER BY started_at DESC LIMIT 1")
    if run_df.empty:
        raise HTTPException(
            status_code=404,
            detail="No successful pipeline run found. Run pipeline.py first."
        )
    run_id    = run_df['run_id'].iloc[0]
    model_list = [m.strip() for m in models.split(',')]
    placeholders = ','.join('?' * len(model_list))

    fc_df = _query(conn,
        f"SELECT forecast_date, model, predicted_price, "
        f"lower_ci_95, upper_ci_95, horizon_day "
        f"FROM forecasts "
        f"WHERE run_id=? AND route=? AND model IN ({placeholders}) "
        f"ORDER BY model, forecast_date",
        (run_id, route) + tuple(model_list)
    )

    if fc_df.empty:
        raise HTTPException(
            status_code=404,
            detail=f"No forecasts found for route '{route}' in run {run_id}."
        )

    # Cap to requested horizon
    fc_df = fc_df[fc_df['horizon_day'] <= horizon]

    # Build response
    forecasts = []
    best_model, best_mape = None, np.inf

    for model in fc_df['model'].unique():
        sub = fc_df[fc_df['model'] == model]
        pts = [
            ForecastPoint(
                date=row['forecast_date'],
                predicted_price=round(row['predicted_price'], 2),
                lower_ci=round(row['lower_ci_95'], 2),
                upper_ci=round(row['upper_ci_95'], 2),
                horizon_day=int(row['horizon_day'])
            )
            for _, row in sub.iterrows()
        ]
        preds = sub['predicted_price'].values
        forecasts.append(ModelForecast(
            model=model, points=pts,
            mean_price=round(float(preds.mean()), 2),
            min_price =round(float(preds.min()),  2),
            max_price =round(float(preds.max()),  2),
        ))

    # Recommend best model from DB performance_metrics if available
    perf = _query(conn,
        "SELECT model, mape FROM performance_metrics "
        "WHERE run_id=? AND route=? AND segment='Overall' "
        "ORDER BY mape ASC LIMIT 1",
        (run_id, route))
    recommended = perf['model'].iloc[0] if not perf.empty else 'Standalone LSTM'

    return ForecastResponse(
        route=route,
        generated_at=datetime.utcnow().isoformat() + 'Z',
        horizon_days=horizon,
        forecasts=forecasts,
        recommended_model=recommended,
        note=f"Sourced from pipeline run {run_id}. "
             f"Re-run pipeline.py to update forecasts."
    )


# ═════════════════════════════════════════════════════════════════════════════
# ENDPOINT 4 — CUSTOM ON-DEMAND FORECAST  (live inference)
# ═════════════════════════════════════════════════════════════════════════════
@app.post(
    "/forecast/custom",
    response_model=ForecastResponse,
    summary="On-demand forecast from user-supplied prices",
    tags=["Forecasts"],
    description=(
        "Accepts a list of historical daily prices and returns forecasts from "
        "all available trained models.  Unlike /forecast/latest, this endpoint "
        "**runs live inference** using the loaded model artifacts, so response "
        "time is longer (1–10 seconds depending on hardware).  "
        "Intended for scenario analysis, what-if pricing, and one-off route "
        "assessments where the pipeline has not yet been run for that route."
    )
)
def forecast_custom(request: CustomForecastRequest):
    if not registry.available_models:
        raise HTTPException(
            status_code=503,
            detail=(
                "No model artifacts loaded. "
                f"Check {ARTIFACT_DIR} contains the required .pkl and .keras files. "
                f"Load errors: {registry._errors}"
            )
        )

    prices   = np.array(request.prices)
    horizon  = request.horizon
    conf     = request.confidence
    z        = float(__import__('scipy').stats.norm.ppf((1 + conf) / 2))
    start_dt = datetime.utcnow().date() + timedelta(days=1)
    start_dt = datetime.combine(start_dt, datetime.min.time())

    forecasts      = []
    arima_fc_arr   = None
    arima_resid    = None
    arima_std      = float(np.std(prices) * 0.3)

    # ── ARIMA ──────────────────────────────────────────────────────────────
    if 'ARIMA' in registry.available_models:
        arima_fc_arr, arima_std, arima_resid = _arima_forecast(prices, horizon)
        lo, hi = _build_ci(arima_fc_arr, arima_std, conf)
        forecasts.append(_package_forecast(
            'ARIMA', arima_fc_arr, lo, hi, start_dt))

    # ── Standalone LSTM ────────────────────────────────────────────────────
    if 'Standalone LSTM' in registry.available_models:
        sa_fc  = _sa_lstm_forecast(prices, horizon)
        sa_std = float(np.std(sa_fc) * 0.5)   # empirical CI width
        lo, hi = _build_ci(sa_fc, sa_std, conf)
        forecasts.append(_package_forecast(
            'Standalone LSTM', sa_fc, lo, hi, start_dt))

    # ── ARIMA-LSTM Hybrid ─────────────────────────────────────────────────
    if 'ARIMA-LSTM Hybrid' in registry.available_models:
        if arima_fc_arr is None:
            arima_fc_arr, arima_std, arima_resid = _arima_forecast(prices, horizon)
        resid    = arima_resid if arima_resid is not None else np.zeros(len(prices))
        hy_fc    = _hybrid_forecast(arima_fc_arr, resid, horizon)
        hy_std   = float(np.std(hy_fc) * 0.45)
        lo, hi   = _build_ci(hy_fc, hy_std, conf)
        forecasts.append(_package_forecast(
            'ARIMA-LSTM Hybrid', hy_fc, lo, hi, start_dt))

    return ForecastResponse(
        route='CUSTOM',
        generated_at=datetime.utcnow().isoformat() + 'Z',
        horizon_days=horizon,
        forecasts=forecasts,
        recommended_model='Standalone LSTM',
        note=(
            f"Live inference on {len(prices)} input prices. "
            f"{int(conf*100)}% confidence intervals computed from "
            f"residual standard deviation."
        )
    )


# ═════════════════════════════════════════════════════════════════════════════
# ENDPOINT 5 — PERFORMANCE METRICS
# ═════════════════════════════════════════════════════════════════════════════
@app.get(
    "/performance",
    response_model=PerformanceResponse,
    summary="Model performance metrics",
    tags=["Evaluation"],
    description=(
        "Returns MAE, RMSE, MAPE and R² for each model.  "
        "If the database contains performance_metrics rows (populated once "
        "forecast dates have passed and actuals are recorded), those are "
        "returned.  Otherwise the endpoint falls back to the thesis test-set "
        "results from the 2016-2020 NBO-MBA evaluation, clearly labelled as "
        "such.  This prevents the endpoint from returning empty data before "
        "the pipeline has accumulated enough actuals."
    )
)
def get_performance(
    route: str = Query('NBO-MBA', description="Route code"),
    conn:  sqlite3.Connection = Depends(get_db)
):
    run_df = _query(conn,
        "SELECT run_id FROM pipeline_runs "
        "WHERE status='SUCCESS' ORDER BY started_at DESC LIMIT 1")

    if not run_df.empty:
        run_id = run_df['run_id'].iloc[0]
        perf   = _query(conn,
            "SELECT model, segment, segment_type, mae, rmse, mape, r2, n_obs "
            "FROM performance_metrics "
            "WHERE run_id=? AND route=? ORDER BY model, segment",
            (run_id, route))

        if not perf.empty:
            return PerformanceResponse(
                route=route,
                results=perf.to_dict(orient='records'),
                source='database'
            )

    # Fallback: thesis test-set results
    return PerformanceResponse(
        route='NBO-MBA (thesis test set)',
        results=THESIS_TEST_RESULTS,
        source='thesis_test_set'
    )


# ═════════════════════════════════════════════════════════════════════════════
# ENDPOINT 6 — PIPELINE AUDIT LOG
# ═════════════════════════════════════════════════════════════════════════════
@app.get(
    "/pipeline/runs",
    response_model=List[PipelineRun],
    summary="Pipeline execution history",
    tags=["Infrastructure"],
    description=(
        "Returns the N most recent pipeline execution records.  Useful for "
        "monitoring whether the daily cron job is running successfully, and "
        "for auditing which data version produced a given forecast.  "
        "Each forecast row in the database references its run_id so the full "
        "provenance chain is traceable."
    )
)
def pipeline_runs(
    n:    int = Query(10, ge=1, le=100, description="Number of runs to return"),
    conn: sqlite3.Connection = Depends(get_db)
):
    df = _query(conn,
        "SELECT run_id, started_at, finished_at, status, "
        "n_rows_raw, n_rows_processed, n_routes "
        "FROM pipeline_runs ORDER BY started_at DESC LIMIT ?",
        (n,))
    if df.empty:
        return []
    df = df.where(pd.notna(df), None)
    return df.to_dict(orient='records')



# ═════════════════════════════════════════════════════════════════════════════
# ENDPOINT 7 — ACTUALS DATA
# ═════════════════════════════════════════════════════════════════════════════
@app.get(
    "/data/actuals",
    summary="Retrieve recorded actual prices",
    tags=["Data"],
    description=(
        "Returns actual departure-date prices recorded by the pipeline after "
        "flights have operated.  Used by the dashboard to overlay historical "
        "actuals on the forecast chart and to compute live error metrics. "
        "Returns an empty records list if no actuals have been recorded yet."
    )
)
def data_actuals(
    route:  str = Query("ALL", description="Route code, e.g. NBO-MBA"),
    limit:  int = Query(90,  ge=1, le=1000, description="Max rows to return"),
    start_date: str = Query(None, description="ISO date e.g. 2021-01-01"),
    end_date:   str = Query(None, description="ISO date e.g. 2021-01-31"),
    conn:   sqlite3.Connection = Depends(get_db)
):
    try:
        filters = ["(route = ? OR ? = 'ALL')"]
        params  = [route, route]

        if start_date:
            filters.append("departure_date >= ?")
            params.append(start_date)
        if end_date:
            filters.append("departure_date <= ?")
            params.append(end_date)

        params.append(limit)
        where = " AND ".join(filters)

        df = _query(conn,
            f"SELECT departure_date, actual_price, booking_window, "
            f"departure_month FROM actuals "
            f"WHERE {where} "
            f"ORDER BY departure_date ASC LIMIT ?",   # ASC so chart renders left→right
            tuple(params))

        if df.empty:
            return {"route": route, "records": []}
        df = df.where(pd.notna(df), None)
        return {"route": route, "records": df.to_dict(orient="records")}
    except Exception:
        return {"route": route, "records": []}


# ═════════════════════════════════════════════════════════════════════════════
# ENTRY POINT
# ═════════════════════════════════════════════════════════════════════════════
if __name__ == '__main__':
    uvicorn.run(
        "api:app",
        host    = "0.0.0.0",
        port    = 8000,
        reload  = True,   # auto-reload on file save — disable in production
        workers = 1,      # single worker: Keras models are not fork-safe
    )
